version: '3.0'
services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
